One way to create a numpy array is from existing object such as a list.

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]
type(mylist)

list

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
type(mylist)

list

If you want to numpy array type, you have to assign. As you can see up, the type of mylist still is list.

In [7]:
arr = np.array(mylist)
type(arr)

numpy.ndarray

In [8]:
arr

array([1, 2, 3])

nested lists to numpy array matrix

In [9]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
mymatrix = np.array(mylist)

In [12]:
mymatrix.shape

(3, 3)

built-in methods

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [50]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [51]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [52]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [53]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [21]:
# Yukarıda yaptığını normal python list ile yapamazsın

Lets go continue with a couple of more ways of creating new numpy arrays.


We have ability to create linearly spaced arrays and that returns evenly spaced numbers over a specified interval.

In [55]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [56]:
# for identity matrix

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Sometimes when you're trying to model data it's reallt nice to just be able to quickly create some

## Part 2

In [25]:
np.random.rand(1)

array([0.20046642])

In [57]:
np.random.rand(5,5)

array([[0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998],
       [0.78517596, 0.19967378, 0.51423444, 0.59241457, 0.04645041],
       [0.60754485, 0.17052412, 0.06505159, 0.94888554, 0.96563203]])

In [27]:
# for normal distribution:
np.random.randn(5)

array([-1.2186794 , -0.82387476,  0.03994033,  0.36005925, -1.83091669])

In [59]:
# if you want your distribution
mean = 5
sd = 1
np.random.normal(mean,sd,(5,5))

array([[4.39974615, 5.94743982, 5.291034  , 4.36444026, 3.97844781],
       [4.83824461, 4.4663512 , 4.99447214, 4.77054955, 5.38934891],
       [3.73488089, 6.09199226, 7.77831304, 6.19363972, 5.21863832],
       [5.88176104, 3.99091466, 3.41670579, 5.77370042, 4.46185834],
       [3.6533219 , 4.11940873, 3.8694477 , 5.13442888, 5.58212279]])

In [60]:
np.random.normal(mean,sd,5)

array([5.88774846, 5.89433233, 5.7549978 , 4.79283411, 4.37652261])

In [61]:
np.random.randint(1,100,3)

array([41, 28,  7])

In [30]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [32]:
arr = np.arange(25)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr = np.random.randint(0,50,10)

In [35]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [36]:
arr.shape

(25,)

In [37]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
# max and min numpy arrays

In [39]:
ranarr.max()

39

In [40]:
ranarr.min()

2

In [41]:
# indexes of max and minimum

In [42]:
ranarr.argmax()

7

In [43]:
ranarr.argmin()

9

In [45]:
ranarr.dtype

dtype('int64')

# Numpy Index Selection

In [86]:
arr = np.arange(0,11)

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr[8]

8

In [89]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
arr[:5]

array([0, 1, 2, 3, 4])

In [91]:
arr[-2:]

array([ 9, 10])

In [92]:
arr[5:-2]

array([5, 6, 7, 8])

numpy array is different than python list because it allow you to broadcast functions and operations across this.

In [93]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
new_arr = arr/2

In [96]:
new_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [97]:
new_arr = arr**2

In [98]:
new_arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [99]:
#slicing array still directly pointing to original array.

In [100]:
#which means when I call my original array notice that the first five elements have all been changed

In [101]:
slice_of_arr = arr[0:6]

In [102]:
slice_of_arr[:] = 99

In [103]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [104]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [105]:
# So thats sort of broadcasting of a reassigment based off aslice 
#like this that will affect your original array
#So always keep that in mind if you didnt want to the original array affected
#you need to be explicit copy

In [106]:
arr_copy = arr.copy()

### Indexing on 2d array

In [108]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [110]:
arr_2d[0:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [112]:
arr_2d[0:2, :-1]

array([[ 5, 10],
       [20, 25]])

In [115]:
# if you want take  10 and 25. What should you do?

In [119]:
arr_2d[:-1,1]

array([10, 25])

In [123]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [122]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

### Conditional Arrays

In [140]:
arr = np.arange(1,11)

In [141]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [142]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [143]:
bool_arr = arr>4

In [144]:
 arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [145]:
arr[arr>=6]

array([ 6,  7,  8,  9, 10])

# NumPy Operations

In [146]:
arr = np.arange(0,11)

In [147]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [149]:
arr/arr

<ipython-input-149-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [150]:
# As you can see above, numpy didnt give full error only warning

#### Some operations

In [151]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [152]:
np.log(arr)

<ipython-input-152-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [153]:
np.sum(arr)

55

In [156]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [161]:
arr.mean()

5.0

In [162]:
arr.sum()

55

In [163]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [164]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [165]:
arr_2d.shape

(3, 4)

In [166]:
arr_2d.sum()

78

In [167]:
# GIVE ME THE SUM, ACROSS THE ROWS
arr_2d.sum(axis = 0)

array([15, 18, 21, 24])

In [168]:
arr_2d.sum(axis = 1)

array([10, 26, 42])