### There are 3 different functionS to create tensor. One of them is the copy of the numpy array. So it doesn't affected from changes in the original array. Because these points different memory locations.
## CREATE TENSOR

In [1]:
import torch 
import numpy as np

In [2]:
torch.__version__

'1.6.0'

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
arr.dtype

dtype('int64')

In [5]:
type(arr)

numpy.ndarray

In [6]:
tensor1 = torch.from_numpy(arr)

In [7]:
type(tensor1)

torch.Tensor

In [8]:
tensor1

tensor([1, 2, 3, 4, 5])

In [9]:
tensor2 = torch.as_tensor(arr)

In [10]:
tensor2

tensor([1, 2, 3, 4, 5])

In [34]:
my_arr = np.arange(0,12).reshape(4,3)

In [35]:
my_arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
my_tensor_copy = torch.tensor(my_arr)

In [37]:
my_tensor_exact = torch.from_numpy(my_arr)

In [38]:
my_arr[0][0] = 9999

In [39]:
my_tensor_copy # didnt change

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [40]:
my_tensor_exact # changed

tensor([[9999,    1,    2],
        [   3,    4,    5],
        [   6,    7,    8],
        [   9,   10,   11]])

## CREATE TENSOR FROM SCRATCH

In [41]:
new_arr = np.array([1,2,3])

In [42]:
torch.tensor(new_arr) #integer

tensor([1, 2, 3])

In [43]:
torch.Tensor(new_arr) #float

tensor([1., 2., 3.])

In [44]:
my_tensor = torch.Tensor(new_arr)

In [45]:
my_tensor.dtype

torch.float32

In [46]:
torch.empty(4,2)

tensor([[ 0.0000e+00, -8.5899e+09],
        [ 0.0000e+00, -8.5899e+09],
        [ 8.4078e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])

In [47]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [48]:
torch.zeros(4,3,dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [49]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [50]:
torch.arange(0,18,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [51]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [52]:
torch.linspace(0,18,12)

tensor([ 0.0000,  1.6364,  3.2727,  4.9091,  6.5455,  8.1818,  9.8182, 11.4545,
        13.0909, 14.7273, 16.3636, 18.0000])

In [53]:
my_tensor = torch.tensor([1,2,3])

In [54]:
my_tensor.dtype

torch.int64

In [56]:
my_tensor = my_tensor.type(torch.int32)

In [57]:
my_tensor.dtype

torch.int32

### Create Random Tensor

In [58]:
torch.rand(4,3) # uniform distribution

tensor([[0.1618, 0.2642, 0.2460],
        [0.0563, 0.4695, 0.2152],
        [0.0690, 0.9837, 0.2826],
        [0.2296, 0.3612, 0.4670]])

In [59]:
torch.randn(4,3) # standard normal distribution

tensor([[ 0.3351,  1.1869, -1.2400],
        [-0.7249, -0.3798,  1.4571],
        [-0.9080, -0.2850, -0.0399],
        [-1.3708, -0.0069, -1.3190]])

In [60]:
torch.randint(low=0,high=10,size=(5,5))

tensor([[3, 5, 7, 4, 6],
        [4, 2, 3, 8, 5],
        [4, 8, 9, 4, 3],
        [5, 1, 7, 0, 7],
        [6, 3, 9, 7, 3]])

In [65]:
x = torch.zeros(5)

In [66]:
x

tensor([0., 0., 0., 0., 0.])

In [67]:
x.shape

torch.Size([5])

In [68]:
torch.rand_like(x)

tensor([0.9245, 0.0937, 0.5935, 0.4414, 0.7827])

In [69]:
torch.randn_like(x)

tensor([ 0.8141, -1.5173, -1.4000, -1.1011, -0.2789])

In [73]:
torch.randint_like(x,low=5,high=11)

tensor([10., 10.,  8.,  6.,  5.])

#### HER ZAMAN AYNI NEURAL NETWORK U ÜRETMEK İÇİN RANDOM DEĞERLERİN HEP AYNI OLMASINI İSTERSEN:

In [74]:
torch.manual_seed(42)

In [75]:
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [76]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [77]:
# yukarıda gördüğün gibi bu sefer farklı random değerler üretti.
# yani her defasında seed kullanman lazım. 
# seed bir kerelik aynı seed değerinden random sayı üretir.

# TENSOR OPERATIONS

In [78]:
x = torch.arange(6).reshape(3,2)

In [79]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [80]:
x[1,1] 

tensor(3)

In [81]:
type(x[1,1]) #type ı hale tensor

torch.Tensor

In [82]:
x[:,1] # row döndürdü 1x3

tensor([1, 3, 5])

In [83]:
# 3x1 olması için:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [84]:
x = torch.arange(10)

In [85]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [87]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [89]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
x = x.reshape(2,5)

In [91]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [92]:
x = torch.arange(10)

In [93]:
x.shape

torch.Size([10])

In [94]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [95]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
z = x.view(2,5)

In [97]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [98]:
# view reflects the essential data. Yani z yi değiştirirsem x de değişir

In [99]:
z[0] = 5

In [100]:
z

tensor([[5, 5, 5, 5, 5],
        [5, 6, 7, 8, 9]])

In [101]:
x

tensor([5, 5, 5, 5, 5, 5, 6, 7, 8, 9])

In [102]:
x = torch.arange(10)

In [103]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
x.shape

torch.Size([10])

In [105]:
# INFER what the 2d dimension if use -1 

In [106]:
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [107]:
a = torch.tensor([1.,2.,3.])

In [108]:
b = torch.tensor([4.,5.,6.])

In [109]:
a + b

tensor([5., 7., 9.])

In [110]:
torch.add(a,b)

tensor([5., 7., 9.])

In [111]:
# a = a + b
# a = a.mul(b)

In [112]:
a.add_(b) #her aritmetik fonksiyon icin yapabiliri

tensor([5., 7., 9.])

In [113]:
a

tensor([5., 7., 9.])

# Tensor operaions 2

In [117]:
a = torch.tensor([[0,2,4],[1,2,5]])
b = torch.tensor([[6,7],[8,9],[10,11]])

### Yukarıda yaptıklarımız element-wise operationlardı. Matrixleri çarpmanın ise iki yolu var:

#### Dot product
#### True two dimensional multiplication

In [118]:
a.shape

torch.Size([2, 3])

In [119]:
b.shape

torch.Size([3, 2])

In [120]:
torch.mm(a,b)

tensor([[56, 62],
        [72, 80]])

In [121]:
a @ b

tensor([[56, 62],
        [72, 80]])

In [123]:
### L2, Euclidean norm
x = torch.tensor([2.,3.,4.,5.])

In [124]:
x.norm()

tensor(7.3485)

In [125]:
x.numel()

4

In [126]:
len(x)

4

In [127]:
a

tensor([[0, 2, 4],
        [1, 2, 5]])

In [128]:
len(a)

2

In [129]:
a.numel()

6