In [34]:
import torch

In [35]:
x = torch.tensor(2.0, requires_grad=True)

In [36]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1

In [37]:
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [38]:
type(y)

torch.Tensor

In [39]:
y.backward()

In [40]:
x.grad

tensor(93.)

In [41]:
x = torch.tensor([[1.,2.,3.],[3.,2.,1.]],requires_grad=True)

In [42]:
print(x)

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)


In [43]:
y = 3*x + 2

In [44]:
print(y)

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)


In [45]:
# second layer:
z = 2*y**2

In [46]:
print(z)

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)


In [47]:
#final layer:
out = z.mean()

In [48]:
print(out)

tensor(140., grad_fn=<MeanBackward0>)


### Now we are gonna do is we're going to perform back propogation to find the gradient of X with respect to this output layer.

In [49]:
out.backward()

In [19]:
print(x.grad)

tensor([[10., 16., 22.],
        [22., 16., 10.]])
